// build.mjs — regenerates defuddle.mjs, the one file read.ts takes from npm.
//
// Run by `go generate ./internal/web`. CI runs it too and fails on a diff, so
// the committed bundle is always the one these pinned versions produce.
//
// Every bundled package is MIT, ISC or BSD, and each of those licences asks for
// its notice to travel with the code. esbuild keeps only /*! comments, which
// most of these packages do not have, so their LICENSE files are collected
// from the metafile and lead the bundle. A package without one fails the
// build rather than shipping unattributed.

import { build } from "esbuild";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const out = "defuddle.mjs";
const result = await build({
	entryPoints: ["bundle.mjs"],
	bundle: true,
	platform: "node",
	format: "esm",
	minify: true,
	legalComments: "none",
	metafile: true,
	write: false,
	outfile: out,
	logLevel: "error",
});

const packages = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
	const at = input.lastIndexOf("node_modules/");
	if (at < 0) continue;
	const segments = input.slice(at + "node_modules/".length).split("/");
	packages.add(input.slice(0, at) + join("node_modules", ...segments.slice(0, segments[0].startsWith("@") ? 2 : 1)));
}

let notices = "";
for (const dir of [...packages].sort()) {
	const { name, version } = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
	const file = readdirSync(dir).find((f) => /^(licen[cs]e|copying)/i.test(f));
	if (!file) throw new Error(`${name} is bundled but has no LICENSE file`);
	const text = readFileSync(join(dir, file), "utf8").trim().replaceAll("*/", "* /");
	notices += `\n${name}@${version}\n\n${text}\n`;
}

const banner = `/*\n * Generated by build.mjs; do not edit. Bundles defuddle and linkedom for read.ts.\n * Licences of every bundled package follow.\n${notices}*/\n`;
writeFileSync(out, banner + result.outputFiles[0].text);
