name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [tests, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      pull-requests: read
